"""Ask Jev one batched request per text: the direct AI/not question plus a speculative fan-out.

Every question is evaluated in parallel against the same state, so the fan-out is nearly free
(~35 tokens each) and code can combine the signals afterwards. Resumable: rows already in
data/preds.jsonl are skipped.

  python3 run.py [data/sample.parquet] [data/preds.jsonl] [--limit N] [--sets raid,hc3]
"""
import duckdb, json, os, sys, threading, time
from concurrent.futures import ThreadPoolExecutor
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jev

# The one question Pangram answers, asked directly.
PRIMARY = {
    "ai": {"type": "noul", "instructions":
           "This text was written by an AI language model (such as ChatGPT, Claude, Llama or "
           "GPT-4), rather than written by a human being."},
    "author": {"type": "choice", "criteria": {
        "human": "A person wrote this themselves, in their own words.",
        "machine": "A language model generated this text."}},
    "machineness": {"type": "score", "criteria": [
        "Unmistakably a particular person writing in their own voice",
        "Could plausibly be either a person or a model",
        "Unmistakably the output of a language model"]},
}

# Speculative fan-out: the register cues a detector would key on. Positive = machine-leaning
# except the six marked human-leaning, which code flips.
FANOUT = {
    "generic": "The prose is generic: swap the topic and most of the sentences would still work.",
    "hedged": "The writing hedges: it qualifies its claims, gives balanced both-sides framing, and avoids committing to a position.",
    "listy": "The text is organised with visible scaffolding: numbered points, bullets, headings, or parallel bullet-like sentences.",
    "no_specifics": "The text contains almost no concrete particulars: no names, numbers, dates, places or checkable details.",
    "assistant_tone": "It reads like a helpful assistant explaining a topic to a reader, rather than a person saying something.",
    "summary_close": "It closes by summarising or restating itself, in the manner of 'in conclusion' or 'overall'.",
    "uniform_rhythm": "The sentences are uniform in length and construction, with little rhythmic variation.",
    "clean_mechanics": "The text is mechanically flawless: no typos, no grammatical slips, no inconsistent punctuation.",
    "formal_diction": "The diction is elevated and nominalised: words like utilize, significant, crucial, multifaceted, and abstract nouns where a verb would do.",
    "dash_triples": "It leans on em dashes, or on three-part parallel lists, as a habit of style.",
    "template": "It follows a recognisable template: a framing opening, an even middle, a tidy closing line.",
    "addressee": "It addresses the reader directly, offers help, or invites follow-up questions.",
    "safe_register": "It is careful and inoffensive in a way that avoids anything a person might get in trouble for saying.",
    # human-leaning
    "h_lived": "The writer reports something they personally lived through, with details only they would know.",
    "h_voice": "The writing has an idiosyncratic voice: slang, jokes, swearing, abbreviations, personal verbal tics.",
    "h_errors": "The text contains typos, grammatical slips, or casual punctuation that a careless writer left in.",
    "h_stake": "The writer takes a strong specific position they could be wrong about.",
    "h_emotion": "The text carries a specific emotion the writer is actually feeling, rather than describing emotions in general.",
    "h_digress": "The text digresses, changes direction mid-way, or leaves a thought unfinished.",
}

# Alternative phrasings of the one question, asked together on a held-out dev slice
# (data/dev.parquet) so the reported number is not hostage to one wording. `run.py --probe`.
PROBE = {
    "v_plain": {"type": "noul", "instructions":
                "This text was written by an AI language model (such as ChatGPT, Claude, Llama or "
                "GPT-4), rather than written by a human being."},
    "v_human_inv": {"type": "noul", "instructions":
                    "A person sat down and wrote this text themselves, in their own words."},
    "v_rich": {"type": "noul", "instructions": {
        "what": "The text was generated by a large language model rather than written by a person.",
        "cues": ["even, fluent prose with no typos or false starts",
                 "generic coverage of a topic rather than a particular person's point",
                 "hedged, balanced, inoffensive framing",
                 "explicit structure: framing opening, tidy closing, parallel sentences",
                 "assistant register: explaining to a reader, offering to help"],
        "not_for": ["careful or formal human writing, such as a published abstract, an edited news "
                    "report, an encyclopaedia entry or a professional review -- these are human",
                    "text a person dictated or typed casually but cleanly"]}},
    "v_choice_rich": {"type": "choice", "criteria": {
        "human": {"what": "A person wrote this themselves.",
                  "examples": ["a reddit comment", "a published news article", "a poem",
                               "a wikipedia paragraph", "a product review", "a recipe someone typed",
                               "a scientific abstract written by its authors"]},
        "machine": {"what": "A language model produced this text, with or without a human prompt.",
                    "examples": ["a chatbot answer", "a model continuation of an article",
                                 "a model-written story or review"]}}},
    "v_score5": {"type": "score", "criteria": [
        "Certainly a person wrote this",
        "Probably a person",
        "Genuinely unclear",
        "Probably a language model",
        "Certainly a language model generated this"]},
    "v_editor": {"type": "noul", "instructions":
                 "An experienced editor, asked to sort this pile into 'written by a person' and "
                 "'generated by a chatbot', would put this text in the chatbot pile."},
}

QUESTIONS = dict(PRIMARY, **{k: {"type": "noul", "instructions": v} for k, v in FANOUT.items()},
                 **{k: v for k, v in PROBE.items() if k != "v_plain"})

def main():
    SRC = sys.argv[1] if len(sys.argv) > 1 and not sys.argv[1].startswith("-") else "data/sample.parquet"
    OUT = sys.argv[2] if len(sys.argv) > 2 and not sys.argv[2].startswith("-") else "data/preds.jsonl"
    argv = " ".join(sys.argv)
    Q = PROBE if "--probe" in argv else QUESTIONS
    limit = int(argv.split("--limit")[1].split()[0]) if "--limit" in argv else None
    sets = argv.split("--sets")[1].split()[0].split(",") if "--sets" in argv else None

    con = duckdb.connect()
    rows = con.execute(f"select uid, text from '{SRC}'"
                       + (f" where set in {tuple(sets) if len(sets)>1 else repr(tuple(sets)[0:1])}" if sets else "")
                       ).fetchall()
    done = set()
    if os.path.exists(OUT):
        done = {json.loads(l)["uid"] for l in open(OUT)}
    rows = [r for r in rows if r[0] not in done]
    if limit:
        rows = rows[:limit]
    print(f"{len(rows)} to ask ({len(done)} already done), {len(Q)} questions each", flush=True)

    lock, f, st = threading.Lock(), open(OUT, "a"), {"n": 0, "tok": 0, "t0": time.time()}

    def work(r):
        uid, text = r
        try:
            res = jev.ask(text, Q)
        except Exception as e:
            with lock: print("ERR", uid, str(e)[:120], flush=True)
            return
        a = res["answers"]
        row = {"uid": uid}
        for k, v in a.items():
            row[k] = v.get("noul", v.get("score"))
            if v["type"] == "choice":
                row[k] = v["probabilities"].get("machine")
                row[k + "_conf"] = v["confidence"]
        with lock:
            f.write(json.dumps(row) + "\n"); st["n"] += 1; st["tok"] += res["usage"]["input_tokens"]
            if st["n"] % 250 == 0:
                el = time.time() - st["t0"]
                print(f"{st['n']}/{len(rows)}  {el/60:.1f}m  ${st['tok']*jev.PRICE:.3f}  {st['n']/el:.1f}/s",
                      flush=True); f.flush()

    with ThreadPoolExecutor(24) as ex:
        list(ex.map(work, rows))
    f.close()
    print(f"DONE {st['n']} rows, ${st['tok']*jev.PRICE:.3f}, {(time.time()-st['t0'])/60:.1f} min", flush=True)


if __name__ == "__main__":
    main()
